fix(mozconfig): drop MOZ_SOURCE_REPO export conflicting with comm-release
mach configure error:
ConflictingOptionError: Cannot add 'MOZ_SOURCE_REPO=https://hg.mozilla.org/releases/comm-release'
to the implied set because it conflicts with MOZ_SOURCE_REPO=https://github.com/zen-browser/desktop
from the mozconfig set