fix(mozconfig): drop MOZ_SOURCE_CHANGESET export conflicting with comm-release
mach configure error:
InvalidOptionError: 'MOZ_SOURCE_CHANGESET=f8ebd3f...' implied by 'MOZ_SOURCE_CHANGESET'
conflicts with the value implied by the comm tree